# configuration for "master" branch
# build in Release mode 
-
  branches:
    only:
      - master
  version: 2.1.0.{build}
  configuration: Release
  platform: Any CPU
  build:
    verbosity: minimal
  build_script:
    - msbuild GoogleMapsServices.sln /p:Configuration=Release
    - msbuild GoogleMapsServices.sln /p:Configuration=Release-Net35
    - msbuild GoogleMapsServices.sln /p:Configuration=Release-Net40
    - nuget pack src/Client/Client.nuspec -Version %APPVEYOR_BUILD_VERSION%
  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
  assembly_info:
    patch: true
    assembly_version: '{version}'
    assembly_file_version: '{version}'
  test: on
  artifacts: 
    - path: '**\*.nupkg'
  deploy:
    - provider: NuGet
      api_key:
        secure: pi98jdOOgUknVbO9zAh2LJiCCsc48HRZ3sGMvCX7DbkeBglS/T1gPcpGee9oOvqO
      artifact: /.*\.nupkg/
      on:
        appveyor_repo_tag: true       # deploy on tag push only

# configuration for "net35" branch
# build in Release-Net35 mode 
-
  branches:
    only:
      - net35
  version: 2.0.{build}
  configuration: Release-Net35
  platform: Any CPU
  build:
    verbosity: minimal
  test: off

# configuration for "net40" branch
# build in Release-Net40 mode 
-
  branches:
    only:
      - net40
  version: 2.0.{build}
  configuration: Release-Net40
  platform: Any CPU
  build:
    verbosity: minimal
  test: off